
public class Homepage extends javax.swing.JFrame {

  
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        need_blood = new javax.swing.JButton();
        donate_blood = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("  Home Page");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 20, 318, 72);

        need_blood.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        need_blood.setText("For Need Blood");
        need_blood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                need_bloodActionPerformed(evt);
            }
        });
        jPanel1.add(need_blood);
        need_blood.setBounds(158, 104, 254, 63);

        donate_blood.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        donate_blood.setText("For Donate");
        donate_blood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donate_bloodActionPerformed(evt);
            }
        });
        jPanel1.add(donate_blood);
        donate_blood.setBounds(158, 185, 254, 64);

        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(164, 354, 107, 35);

        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(300, 350, 106, 35);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("N.B. : Please Donate Blood for Save a Life");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 280, 260, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\project\\Blood-Donation.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 720, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void need_bloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_need_bloodActionPerformed
                setVisible(false);
                Need_blood obj4 = new Need_blood();
                obj4.setVisible(true);           
    }//GEN-LAST:event_need_bloodActionPerformed

    private void donate_bloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donate_bloodActionPerformed
               setVisible(false);     
               Donate_blood obj5 = new Donate_blood();
                 obj5.setVisible(true);        
    }//GEN-LAST:event_donate_bloodActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
          System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         this.hide();
        Login1 ob= new Login1();
        ob.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton donate_blood;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton need_blood;
    // End of variables declaration//GEN-END:variables
}
